# Generated by Django 4.0.5 on 2022-06-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarafshon', '0002_alter_post_options_alter_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='zarafshon.tag'),
        ),
    ]
