# Generated by Django 4.0.5 on 2022-06-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarafshon', '0003_tag_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=100)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_message', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video'), ('Maqola', 'Maqola'), ('News', 'News')], max_length=6),
        ),
    ]
